$(document).ready(function(){
    $(".flip").click(function(){
        $(".panel").slideToggle();
    })
})
$(document).ready(function(){
    $(".flip2").click(function(){
        $(".panel2").slideToggle();
    })
})
$(document).ready(function(){
    $(".flip3").click(function(){
        $(".panel3").slideToggle();
    })
})